version: '3'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: gokit_backend
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@supabase-postgres:5432/postgres
      REDIS_URL: redis://redis:6379
    ports:
      - "8081:8080"
    volumes:
      - ../backend:/workspace:cached
      - /workspace/tmp/
    working_dir: /workspace
    command: [ "air", "-c", ".air.toml" ]
    networks:
      - gokit-network

  admin_panel:
    build:
      context: ..
      dockerfile: docker/Dockerfile.admin_panel
    container_name: gokit_admin_panel
    restart: always
    depends_on:
      - backend
    ports:
      - "3050:3000"
    tty: true
    volumes:
      - ../admin_panel:/workspace:cached
      - /workspace/node_modules
    working_dir: /workspace
    command: [ "npm", "run", "dev" ]
    networks:
      - gokit-network

networks:
  gokit-network:
    name: gokit-network
    external: false