FROM node:23-bookworm
ENV WATCHPACK_POLLING=true

WORKDIR /workspace

# 依存関係を先にコピーしてキャッシュを活用
COPY admin_panel/package.json admin_panel/package-lock.json ./
RUN npm install

# ソースコードをコピー
COPY admin_panel /workspace/admin_panel

CMD ["npm", "run", "dev"]
