FROM golang:1.24-bookworm

WORKDIR /workspace

# `backend/` の全ファイルを `/workspace` にコピー
COPY backend /workspace

# Airをインストール
RUN go install github.com/air-verse/air@latest

RUN go mod download
RUN go mod tidy

# 実行
CMD ["air", "-c", ".air.toml"]
